---
REGISTER_VERIFICATION_URL: ${ssm:/jobbergate-api/prod/REGISTER_VERIFICATION_URL}
STAGE: ${self:provider.stage}
DATABASE_PASS: ${ssm:/jobbergate-api/prod/DATABASE_PASS}
DATABASE_USER: ${ssm:/jobbergate-api/prod/DATABASE_USER}
DATABASE_NAME: ${ssm:/jobbergate-api/prod/DATABASE_NAME}
DATABASE_HOST:
  ? "Fn::GetAtt"
  :
    - AuroraInstance
    - Endpoint.Address
DATABASE_PORT:
  ? "Fn::GetAtt"
  :
    - AuroraInstance
    - Endpoint.Port
DATABASE_URI:
  Fn::Join:
  - ''
  - - "postgres://"
    - ${ssm:/jobbergate-api/prod/DATABASE_USER}
    - ":"
    - ${ssm:/jobbergate-api/prod/DATABASE_PASS}
    - "@"
    - Fn::GetAtt:
       - AuroraInstance
       - Endpoint.Address
    - ":"
    - Fn::GetAtt:
      - AuroraInstance
      - Endpoint.Port
    - "/"
    - ${ssm:/jobbergate-api/prod/DATABASE_NAME}
CLOUDFRONT_DOMAIN: !GetAtt AssetsDistribution.DomainName

SENTRY_DSN: ${ssm:/jobbergate-api/prod/SENTRY_DSN}
